# Task 1

In [1]:
import pandas as pd
tickets = pd.read_csv('data_safe_copy.csv', index_col = 0)
tickets.head()

                  opened_at   category priority resolution_minutes
ticket_id
TK-0001    2024-03-01 09:00    billing      low                 45
TK-0002    2024-03-01 09:30    account   medium                 30
TK-0003    2024-03-01 10:00  technical     high                 75
TK-0004    2024-03-01 10:30    billing      low                NaN
TK-0005    2024-03-01 11:00    account   medium            unknown

In [2]:
tickets.shape

(500, 4)

In [3]:
tickets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, TK-0001 to TK-0500
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   opened_at           500 non-null    object
 1   category            500 non-null    object
 2   priority            500 non-null    object
 3   resolution_minutes  450 non-null    object
dtypes: object(4)
memory usage: 19.5+ KB

# Task 2

In [4]:
tickets_n = tickets.copy()
tickets_n['opened_at'] = pd.to_datetime(tickets_n['opened_at'])
tickets_n

                    opened_at   category priority resolution_minutes
ticket_id
TK-0001   2024-03-01 09:00:00    billing      low                 45
TK-0002   2024-03-01 09:30:00    account   medium                 30
TK-0003   2024-03-01 10:00:00  technical     high                 75
TK-0004   2024-03-01 10:30:00    billing      low                NaN
TK-0005   2024-03-01 11:00:00    account   medium            unknown
...                       ...        ...      ...                ...
TK-0496   2024-03-01 11:30:00  TECHNICAL     high                 60
TK-0497   2024-03-01 12:00:00    billing    high                  15
TK-0498   2024-03-01 12:30:00    account      low                 90
TK-0499   2024-03-01 13:00:00  technical   medium                120
TK-0500   2024-03-01 13:30:00    billing   medium                 25

[500 rows x 4 columns]

In [5]:
tickets_n['category'] = tickets_n['category'].str.strip().str.lower()
tickets_n['priority'] = tickets_n['priority'].str.strip().str.lower()

In [6]:
tickets_n['category'].unique()

array(['billing', 'account', 'technical'], dtype=object)

In [7]:
tickets_n['priority'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [8]:
tickets_n['opened_at'].unique()

<DatetimeArray>
['2024-03-01 09:00:00', '2024-03-01 09:30:00', '2024-03-01 10:00:00',
 '2024-03-01 10:30:00', '2024-03-01 11:00:00', '2024-03-01 11:30:00',
 '2024-03-01 12:00:00', '2024-03-01 12:30:00', '2024-03-01 13:00:00',
 '2024-03-01 13:30:00']
Length: 10, dtype: datetime64[ns]

# Task 3

In [9]:
tickets_n['resolution_minutes'] = pd.to_numeric(tickets_n['resolution_minutes'],errors="coerce")
tickets_n['resolution_minutes']

ticket_id
TK-0001     45.0
TK-0002     30.0
TK-0003     75.0
TK-0004      NaN
TK-0005      NaN
           ...
TK-0496     60.0
TK-0497     15.0
TK-0498     90.0
TK-0499    120.0
TK-0500     25.0
Name: resolution_minutes, Length: 500, dtype: float64

In [10]:
tickets_n['resolution_minutes'].isna().sum()

100

# Task 4

In [11]:
tickets_clean = tickets_n.dropna(subset = ['resolution_minutes'])
tickets_clean

                    opened_at   category priority  resolution_minutes
ticket_id
TK-0001   2024-03-01 09:00:00    billing      low                45.0
TK-0002   2024-03-01 09:30:00    account   medium                30.0
TK-0003   2024-03-01 10:00:00  technical     high                75.0
TK-0006   2024-03-01 11:30:00  technical     high                60.0
TK-0007   2024-03-01 12:00:00    billing     high                15.0
...                       ...        ...      ...                 ...
TK-0496   2024-03-01 11:30:00  technical     high                60.0
TK-0497   2024-03-01 12:00:00    billing     high                15.0
TK-0498   2024-03-01 12:30:00    account      low                90.0
TK-0499   2024-03-01 13:00:00  technical   medium               120.0
TK-0500   2024-03-01 13:30:00    billing   medium                25.0

[400 rows x 4 columns]

In [12]:
(tickets_clean['resolution_minutes']>=0).all()

True

In [13]:
tickets_clean['resolution_minutes'].mean()

57.5

In [14]:
tickets_clean['resolution_minutes'].max()

120.0

In [15]:
tickets_clean['category'].unique()

array(['billing', 'account', 'technical'], dtype=object)

In [16]:
tickets.shape[0]

500

In [17]:
tickets_clean.shape[0]

400

# Task 5

In [18]:
summary = {'total_records' : tickets.shape[0],
          'clean_records': tickets_clean.shape[0],
          'missing_resolution': tickets_n['resolution_minutes'].isna().sum(),
          'avg_resolution': tickets_clean['resolution_minutes'].mean(),
          'max_resolution': tickets_clean['resolution_minutes'].max()}
summary

{'total_records': 500,
 'clean_records': 400,
 'missing_resolution': 100,
 'avg_resolution': 57.5,
 'max_resolution': 120.0}

In [19]:
summary['total_records'] == (summary['clean_records']+summary['missing_resolution'])

True